CREATE TABLE MEMBER
(
    ID          VARCHAR2(50),
    PWD         NVARCHAR2(50),
    NAME        NVARCHAR2(50),
    GENDER      NCHAR(2),--남성,여성
    AGE         NUMBER(3),
    BIRTHDAY    CHAR(10),--2023-01-02
    PHONE       CHAR(13),--010-1234-2345
    REGDATE     DATE
);

INSERT INTO MEMBER(GENDER) VALUES('남성');

SELECT LENGTHB(GENDER) FROM MEMBER;

DROP TABLE MEMBER;

ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);

ALTER TABLE MEMBER DROP COLUMN AGE;

ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);
